# Generated by Django 5.0 on 2025-12-16 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notesapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="note",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("title",),
                name="unique_active_note_title",
            ),
        ),
    ]
