# Generated by Django 5.0 on 2026-04-21 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_note_unique_active_note_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_active_note_title',
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('title', 'user'), name='unique_active_note_title_per_user'),
        ),
    ]
